CREATE DATABASE my_deal;
USE deal;
CREATE TABLE project (
project_id INT AUTO_INCREMENT PRIMARY KEY,
project_name VARCHAR(50) NOT NULL,
user_id INT
);
CREATE TABLE user (
user_id INT AUTO_INCREMENT PRIMARY KEY,
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
email VARCHAR(128) NOT NULL UNIQUE,
name VARCHAR(128) NOT NULL,
password VARCHAR(50) NOT NULL
);
CREATE TABLE task (
task_id INT AUTO_INCREMENT PRIMARY KEY,
data TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
done ENUM('1','0') NOT NULL DEFAULT '0', 
task_name VARCHAR(128) NOT NULL,
file VARCHAR(255),
done_time DATE NOT NULL,
user_id INT,
project_id INT
)