
      <div class="main_photogallery-item"><a data-fancybox="gallery" href="../assets/img/<?php echo $galleryUrl ?>" data-caption="<?php echo $galleryName ?>" title=""><img src="../assets/img/<?php echo $galleryUrl ?>" alt="" title=""></a></div>
      <div class="main_photogallery-item"><a data-fancybox="gallery" href="../assets/img/<?php echo $galleryUrl ?>" data-caption="<?php echo $galleryName ?>" title=""><img src="../assets/img/<?php echo $galleryUrl ?>" alt="" title=""></a></div>
      <div class="main_photogallery-item"><a data-fancybox="gallery" href="../assets/img/<?php echo $galleryUrl ?>" data-caption="<?php echo $galleryName ?>" title=""><img src="../assets/img/<?php echo $galleryUrl ?>" alt="" title=""></a></div>
      <div class="main_photogallery-item"><a data-fancybox="gallery" href="../assets/img/<?php echo $galleryUrl ?>" data-caption="<?php echo $galleryName ?>" title=""><img src="../assets/img/<?php echo $galleryUrl ?>" alt="" title=""></a></div>
      <div class="main_photogallery-item"><a data-fancybox="gallery" href="../assets/img/<?php echo $galleryUrl ?>" data-caption="<?php echo $galleryName ?>" title=""><img src="../assets/img/<?php echo $galleryUrl ?>" alt="" title=""></a></div>
      <div class="main_photogallery-item"><a data-fancybox="gallery" href="../assets/img/<?php echo $galleryUrl ?>" data-caption="<?php echo $galleryName ?>" title=""><img src="../assets/img/<?php echo $galleryUrl ?>" alt="" title=""></a></div>
      <div class="main_photogallery-item"><a data-fancybox="gallery" href="../assets/img/<?php echo $galleryUrl ?>" data-caption="<?php echo $galleryName ?>" title=""><img src="../assets/img/<?php echo $galleryUrl ?>" alt="" title=""></a></div>
      <div class="main_photogallery-item"><a data-fancybox="gallery" href="../assets/img/<?php echo $galleryUrl ?>" data-caption="<?php echo $galleryName ?>" title=""><img src="../assets/img/<?php echo $galleryUrl ?>" alt="" title=""></a></div>
      <div class="main_photogallery-item"><a data-fancybox="gallery" href="../assets/img/<?php echo $galleryUrl ?>" data-caption="<?php echo $galleryName ?>" title=""><img src="../assets/img/<?php echo $galleryUrl ?>" alt="" title=""></a></div>
      <div class="main_photogallery-item"><a data-fancybox="gallery" href="../assets/img/<?php echo $galleryUrl ?>" data-caption="<?php echo $galleryName ?>" title=""><img src="../assets/img/<?php echo $galleryUrl ?>" alt="" title=""></a></div>
      <!-- <div class="main_photogallery-item"><a data-fancybox="gallery" href="../assets/img/gallery.jpg" data-caption="Фото 1" title=""><img src="../assets/img/gallery.jpg" alt="" title=""></a></div>
      <div class="main_photogallery-item"><a data-fancybox="gallery" href="../assets/img/gallery.jpg" data-caption="Фото 1" title=""><img src="../assets/img/gallery.jpg" alt="" title=""></a></div>
      <div class="main_photogallery-item"><a data-fancybox="gallery" href="../assets/img/gallery.jpg" data-caption="Фото 1" title=""><img src="../assets/img/gallery.jpg" alt="" title=""></a></div>
      <div class="main_photogallery-item"><a data-fancybox="gallery" href="../assets/img/gallery.jpg" data-caption="Фото 1" title=""><img src="../assets/img/gallery.jpg" alt="" title=""></a></div>
      <div class="main_photogallery-item"><a data-fancybox="gallery" href="../assets/img/gallery.jpg" data-caption="Фото 1" title=""><img src="../assets/img/gallery.jpg" alt="" title=""></a></div>
      <div class="main_photogallery-item"><a data-fancybox="gallery" href="../assets/img/gallery.jpg" data-caption="Фото 1" title=""><img src="../assets/img/gallery.jpg" alt="" title=""></a></div>
      <div class="main_photogallery-item"><a data-fancybox="gallery" href="../assets/img/gallery.jpg" data-caption="Фото 1" title=""><img src="../assets/img/gallery.jpg" alt="" title=""></a></div>
     -->